"""Sequential image classification with RENs and R2DNs.

Images are presented one pixel at a time and the network makes a single
prediction from its output at the final timestep.

Code generated by Claude code, checked by Nic Barbara.
"""
import hashlib
import os
import subprocess
from datetime import datetime
from pathlib import Path

import jax
import jax.numpy as jnp
import numpy as np
import optax

from copy import deepcopy

from robustnn import ren
from robustnn import r2dn
from robustnn.utils import count_num_params

from . import data_handling as handler
from .utils import (get_activation, choose_lbdn_width, generate_fname,
                    load_results, save_results)

# Number of inputs per timestep for each task
TASKS = {"rowmnist": 28, "smnist": 1, "psmnist": 1, "scifar10": 3}

# Fixed permutation for psMNIST, generated once and cached to disk
PERMUTATION_SEED = 92916
PERMUTATION_FILE = "./data/mnist/psmnist_permutation.npy"

# Hold out 2000 examples for validation set
N_VAL = 2000
SPLIT_SEED = 1234

# CIFAR-10 statistics to make data processing easier
CIFAR_MEAN = (0.4914, 0.4822, 0.4465)
CIFAR_STD = (0.2023, 0.1994, 0.2010)


def build_model(config, nu, ny=10):
    """Build a REN or R2DN for sequential classification."""
    if config["network"] == "contracting_ren":
        model = ren.ContractingREN(
            nu,
            config["nx"],
            config["nv"],
            ny,
            activation=get_activation(config["activation"]),
            init_method=config["init_method"],
            init_output_zero=config.get("init_output_zero", False),
            do_polar_param=config["polar"],
        )
    elif config["network"] == "contracting_r2dn":
        model = r2dn.ContractingR2DN(
            nu,
            config["nx"],
            config["nv"],
            ny,
            config["nh"],
            activation=get_activation(config["activation"]),
            init_method=config["init_method"],
            init_output_zero=config.get("init_output_zero", False),
            do_polar_param=config["polar"],
        )
    else:
        raise ValueError("Unknown network '{}'".format(config["network"]))
    return model


def pixel_permutation(n=784):
    """Fixed pixel permutation for psMNIST. Identical across all runs.

    `RandomState(92916)` is the permutation convention used across the
    sequential-MNIST literature (it appears in S4's dataloader too).
    """
    if os.path.exists(PERMUTATION_FILE):
        return np.load(PERMUTATION_FILE)
    perm = np.random.RandomState(PERMUTATION_SEED).permutation(n)
    np.save(PERMUTATION_FILE, perm)
    return perm


def permutation_hash(perm):
    """Short hash of the permutation, logged with every psMNIST run."""
    return hashlib.md5(np.asarray(perm, dtype=np.int64).tobytes()).hexdigest()[:8]


def _split_train_val(x, y):
    """Hold out images from the training set for model selection."""
    idx = np.random.RandomState(SPLIT_SEED).permutation(len(x))
    return (x[idx[N_VAL:]], y[idx[N_VAL:]]), (x[idx[:N_VAL]], y[idx[:N_VAL]])


def _augment(x, rng):
    """Random crop with 4-pixel zero padding, then a random horizontal flip.
    """
    x = np.pad(x, ((0, 0), (4, 4), (4, 4), (0, 0)))
    i, j = rng.integers(0, 9, (2, len(x)))
    x = np.stack([x[k, i[k]:i[k]+32, j[k]:j[k]+32] for k in range(len(x))])
    flip = rng.random(len(x)) < 0.5
    x[flip] = x[flip, :, ::-1]
    return x


def load_task(task):
    """Load a task as (train, val, test) splits of images and integer labels.

    MNIST images are in [0,1] with no further normalization, matching S4's
    dataloader. CIFAR-10 stays in [0,1] here so that `to_sequence` can 
    augment before normalizing, as torchvision does.
    """
    if task in ("smnist", "psmnist", "rowmnist"):
        (x, y), (x_test, y_test) = handler.load_mnist()
        if task == "psmnist":
            perm = pixel_permutation()
            x = x.reshape(-1, 784, 1)[:, perm]
            x_test = x_test.reshape(-1, 784, 1)[:, perm]
        elif task == "smnist":
            x, x_test = x.reshape(-1, 784, 1), x_test.reshape(-1, 784, 1)

    elif task == "scifar10":
        (x, y), (x_test, y_test) = handler.load_cifar10()

    else:
        raise ValueError("Unknown task '{}'".format(task))

    train, val = _split_train_val(x, y)
    return train, val, (x_test, y_test)


def to_sequence(x, task, rng=None):
    """Format a batch of images as an input sequence of shape (time, batch, nu).

    Pass `rng` to apply the training-set augmentation (CIFAR-10 only).
    """
    if task == "scifar10":
        if rng is not None:
            x = _augment(x, rng)
        x = ((x - np.array(CIFAR_MEAN)) / np.array(CIFAR_STD)).reshape(-1, 1024, 3)
    return jnp.swapaxes(jnp.asarray(x, dtype=jnp.float32), 0, 1)


def setup_optimizer(config, steps_per_epoch):
    """Adam with the step-wise learning rate cuts
    """
    boundaries = {e*steps_per_epoch: 0.1 for e in config["lr_cuts"]}
    scheduler = optax.piecewise_constant_schedule(config["lr"], boundaries)
    return optax.chain(
        optax.add_decayed_weights(config["weight_decay"]),
        optax.inject_hyperparams(optax.adam)(learning_rate=scheduler),
    )


def train(model, config, train_data, val_data, test_data, verbose=True, init_params=None):
    """Train a model for sequential image classification.

    Args:
        model: REN or R2DN to train.
        config (dict): Training/model config options.
        train_data, val_data, test_data (tuple): (u, y) splits from `load_task`.
        verbose (bool, optional): Whether to print. Defaults to True.

    Returns:
        params: Parameters of the trained model.
        results (dict): Losses, accuracies and timing for each epoch.
    """

    def loss_fn(params, x0, u, y):
        _, logits = model.simulate_sequence(params, x0, u)
        return jnp.mean(
            optax.softmax_cross_entropy_with_integer_labels(logits[-1], y)
        )

    grad_loss = jax.jit(jax.value_and_grad(loss_fn))

    @jax.jit
    def train_step(params, opt_state, x0, u, y):
        loss_value, grads = grad_loss(params, x0, u, y)
        updates, opt_state = optimizer.update(grads, opt_state, params)
        params = optax.apply_updates(params, updates)
        return params, opt_state, loss_value

    @jax.jit
    def predict(params, x0, u):
        _, logits = model.simulate_sequence(params, x0, u)
        return jnp.argmax(logits[-1], axis=-1)

    def accuracy(params, data):
        u, y = data
        batchsize = config["eval_batchsize"]
        correct = 0
        for k in range(0, len(y), batchsize):
            ub = to_sequence(u[k:k+batchsize], task)
            x0 = jnp.zeros((ub.shape[1], model.state_size))
            correct += jnp.sum(predict(params, x0, ub) == y[k:k+batchsize])
        return float(correct) / len(y)

    # Initialise model parameters and optimizer state
    task = config["experiment"]
    u_train, y_train = train_data
    batchsize = config["batchsize"]
    steps_per_epoch = len(y_train) // batchsize

    rng = jax.random.key(config["seed"])
    key1, key2 = jax.random.split(rng)
    init_u = to_sequence(u_train[:batchsize], task)[0]
    init_x = model.initialize_carry(key1, init_u.shape)
    # `init_params` resumes from a previous run's weights. The optimizer state
    # is not saved, so Adam restarts - fine at small learning rates, but it is
    # an approximation to a true continuation.
    params = model.init(key2, init_x, init_u) if init_params is None else init_params

    optimizer = setup_optimizer(config, steps_per_epoch)
    opt_state = optimizer.init(params)

    # Loop through for training
    shuffle_rng = np.random.default_rng(config["seed"])
    augment_rng = shuffle_rng if config.get("augment", True) else None
    train_loss_log, val_acc_log, test_acc_log = [], [], []
    timelog = [datetime.now()]
    for epoch in range(config["epochs"]):

        indx = shuffle_rng.permutation(len(y_train))
        batch_loss = []
        for k in range(steps_per_epoch):
            batch = indx[k*batchsize:(k + 1)*batchsize]
            u = to_sequence(u_train[batch], task, augment_rng)
            y = jnp.array(y_train[batch])
            x0 = jnp.zeros((batchsize, model.state_size))
            params, opt_state, loss_value = train_step(
                params, opt_state, x0, u, y
            )
            batch_loss.append(loss_value)

        # Store losses/accuracies and print training info
        train_loss_log.append(float(jnp.mean(jnp.array(batch_loss))))
        val_acc_log.append(accuracy(params, val_data))
        test_acc_log.append(accuracy(params, test_data))
        timelog.append(datetime.now())
        lr = opt_state[1].hyperparams["learning_rate"]

        if verbose:
            print(f"Epoch: {epoch+1}/{config['epochs']}, "
                  f"Loss: {train_loss_log[-1]:.4f}, "
                  f"Val: {100*val_acc_log[-1]:.2f}%, "
                  f"Test: {100*test_acc_log[-1]:.2f}%, "
                  f"lr: {lr:.3g}, "
                  f"Time: {(timelog[-1] - timelog[-2]).total_seconds():.1f}s")

        # Stop early if we're over the time budget for this run
        hours = (timelog[-1] - timelog[0]).total_seconds() / 3600
        if config.get("time_limit") and hours > config["time_limit"]:
            print(f"Stopping after {epoch+1} epochs: over the {config['time_limit']}h limit.")
            break

    val_acc = np.array(val_acc_log)
    test_acc = np.array(test_acc_log)
    results = {
        "train_loss": np.array(train_loss_log),
        "val_acc": val_acc,
        "test_acc": test_acc,
        "times": timelog,
        "epochs_run": len(val_acc),
        "epoch_time": np.mean([
            (timelog[k+1] - timelog[k]).total_seconds() for k in range(len(val_acc))
        ]),
        "test_at_best_val": float(test_acc[np.argmax(val_acc)]),
        "best_val_acc": float(np.max(val_acc)),
        "best_test_acc": float(np.max(test_acc)),
        "final_test_acc": float(test_acc[-1]),
        "epoch1_test_acc": float(test_acc[0]),
    }
    return params, results


def default_config():
    """Baseline training config."""
    return {
        "experiment": "psmnist",
        "network": "contracting_ren",
        "epochs": 150,
        "lr": 1e-3,
        "lr_cuts": (90,),
        "weight_decay": 1e-5,
        "batchsize": 512,
        "eval_batchsize": 1024,
        "seed": 0,
        "nx": 64,
        "nv": 224,
        "activation": "relu",
        "init_method": "long_memory",
        "init_output_zero": False,
        "polar": True,
    }


def matched_r2dn_config(config, nu, layers=4, ny=10):
    """R2DN config with the same parameter count as a given REN config."""
    c = deepcopy(config)
    c["network"] = "contracting_r2dn"
    c["nv"] = config["nv"] // 2
    nh = choose_lbdn_width(nu, c["nx"], ny, config["nv"], c["nv"], layers)
    c["nh"] = (nh,) * layers
    return c


def git_sha():
    return subprocess.check_output(["git", "rev-parse", "--short", "HEAD"]).decode().strip()


def run(config, verbose=True):
    """Train and evaluate a model on a sequential classification task.

    Args:
        config (dict): Training/model config options.
        verbose (bool, optional): Whether to print. Defaults to True.

    Returns:
        dict: Dictionary of results.
    """
    task = config["experiment"]
    train_data, val_data, test_data = load_task(task)

    # Pilot runs use a subset of the training data to keep the timing honest
    if config.get("train_subset"):
        n = config["train_subset"]
        train_data = (train_data[0][:n], train_data[1][:n])

    model = build_model(config, TASKS[task])

    # Optionally warm-start from a previous run's saved weights
    init_params = None
    if config.get("resume_from"):
        init_params = load_results(Path(config["resume_from"]))[1]

    params, results = train(
        model, config, train_data, val_data, test_data, verbose, init_params
    )

    results["num_params"] = count_num_params(params)
    # From the sequence, not the images: sCIFAR10 images are (32, 32, 3) and
    # only become a length-1024 sequence inside `to_sequence`.
    results["seq_len"] = to_sequence(train_data[0][:1], task).shape[0]
    results["git_sha"] = git_sha()
    if task == "psmnist":
        results["permutation_hash"] = permutation_hash(pixel_permutation())

    save_results(config, params, results)
    return results


def print_summary(config, results):
    """Print the headline metrics for a finished run."""
    _, fname = generate_fname(config)
    print(f"\n{fname}")
    print(f"  Params:            {results['num_params']}")
    print(f"  Epochs run:        {results['epochs_run']}")
    print(f"  Time per epoch:    {results['epoch_time']:.1f}s")
    print(f"  Test @ best val:   {100*results['test_at_best_val']:.2f}%")
    print(f"  Best test acc:     {100*results['best_test_acc']:.2f}%")
    print(f"  Final test acc:    {100*results['final_test_acc']:.2f}%")
    print(f"  Epoch 1 test acc:  {100*results['epoch1_test_acc']:.2f}%")
