"""Plot REN vs R2DN results on sequential image classification.

Produces, for each task:
  - test accuracy vs training epoch
  - test accuracy vs elapsed wall-clock time (the point of the R2DN)
  - a grid of correctly and incorrectly classified test images

and prints a summary table of final accuracies and per-epoch times.

Code generated by Claude code, checked by Nic Barbara.
"""
import jax.numpy as jnp
import numpy as np
import matplotlib.pyplot as plt

from pathlib import Path

dirpath = Path(__file__).resolve().parent

from utils import seqcls
from utils.plot_utils import startup_plotting
from utils import utils

startup_plotting()

MODELS = ["contracting_ren", "contracting_r2dn"]
LABELS = {"contracting_ren": "REN", "contracting_r2dn": "R2DN"}
COLORS = {"contracting_ren": "#009E73", "contracting_r2dn": "#D55E00"}

CIFAR_CLASSES = ["plane", "car", "bird", "cat", "deer",
                 "dog", "frog", "horse", "ship", "truck"]

figpath = dirpath / "../paperfigs/seqcls"


def load_runs(experiment, tag="final"):
    """Load every saved run for an experiment, grouped by model."""
    fpath = dirpath / f"../results/{experiment}/"
    runs = {model: [] for model in MODELS}
    for f in sorted(fpath.glob("*.pickle")):
        config, params, results = utils.load_results(f)
        if config.get("tag") != tag or config["network"] not in runs:
            continue
        runs[config["network"]].append(
            {"config": config, "params": params, "results": results}
        )
    return runs


def aggregate(runs):
    """Mean/min/max test accuracy over seeds, against epochs and elapsed time."""
    acc = 100 * np.array([r["results"]["test_acc"] for r in runs])

    # Elapsed time per epoch, measured from the end of the first epoch so the
    # JIT compilation in epoch 1 doesn't shift the curves
    times = np.array([
        [(t - r["results"]["times"][1]).total_seconds() for t in r["results"]["times"][1:]]
        for r in runs
    ])

    # Interpolate every seed onto a common grid that ends with the shortest
    # run, so no curve is extrapolated past the data it has
    time = np.linspace(0, times[:, -1].min(), acc.shape[1])
    time_acc = np.array([np.interp(time, times[k], acc[k]) for k in range(len(acc))])

    return {
        "acc": acc.mean(axis=0), "acc_min": acc.min(axis=0), "acc_max": acc.max(axis=0),
        "time": time / 3600,
        "time_acc": time_acc.mean(axis=0),
        "time_acc_min": time_acc.min(axis=0),
        "time_acc_max": time_acc.max(axis=0),
    }


def format_plot(xlabel, ylabel, filename, legend_loc="lower right"):
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    plt.legend(loc=legend_loc)
    plt.grid(True, which='both', linestyle=':', linewidth=0.75)
    plt.tight_layout()
    figpath.mkdir(parents=True, exist_ok=True)
    plt.savefig(figpath / f"{filename}.pdf")
    plt.close()


def plot_accuracy(experiment):
    """Test accuracy against epochs and against wall-clock time."""
    runs = load_runs(experiment)
    results = {m: aggregate(runs[m]) for m in MODELS if runs[m]}

    plt.figure(figsize=(3, 2.7))
    for model, r in results.items():
        x = np.arange(1, len(r["acc"]) + 1)
        plt.plot(x, r["acc"], color=COLORS[model], label=LABELS[model])
        plt.fill_between(x, r["acc_min"], r["acc_max"], alpha=0.2, color=COLORS[model])
    format_plot("Training epochs", "Test accuracy (\\%)", f"{experiment}_accuracy")

    plt.figure(figsize=(3, 2.7))
    for model, r in results.items():        
        plt.plot(r["time"], r["time_acc"], color=COLORS[model], label=LABELS[model])
        plt.fill_between(r["time"], r["time_acc_min"], r["time_acc_max"],
                         alpha=0.2, color=COLORS[model])
        plt.scatter(r["time"][-1:], r["time_acc"][-1:], c=COLORS[model], s=20, marker="o")
        # Final mean accuracy, so it is easy to see which model ends up ahead
        plt.axhline(r["acc"][-1], color=COLORS[model], ls="--", lw=1.0, alpha=0.75)
    format_plot("Elapsed training time (h)", "Test accuracy (\\%)",
                f"{experiment}_accuracy_time")


def classify_test_images(run, experiment, n_images=1000):
    """Run a trained model over the first `n_images` of the test set."""
    x, y = seqcls.load_task(experiment)[2]
    x, y = x[:n_images], y[:n_images]

    u = seqcls.to_sequence(x, experiment)
    model = seqcls.build_model(run["config"], u.shape[-1])
    x0 = jnp.zeros((u.shape[1], model.state_size))
    _, logits = model.simulate_sequence(run["params"], x0, u)
    return x, y, np.array(jnp.argmax(logits[-1], axis=-1))


def show_image(ax, image, experiment):
    """Draw a test image as a human sees it, not as the model sees it."""
    if experiment == "scifar10":
        ax.imshow(np.clip(image, 0, 1))
    else:
        # The model reads psMNIST pixels in a fixed random order, so undo the
        # permutation to recover something recognisable
        order = np.argsort(seqcls.pixel_permutation())
        ax.imshow(image[order].reshape(28, 28), cmap="gray")
    ax.set_xticks([])
    ax.set_yticks([])


def plot_example_predictions(experiment, model="contracting_r2dn", n_show=4):
    """Show test images the model classifies correctly and incorrectly.

    The model never sees an image: it reads a length-784 or length-1024 scan of
    pixels, permuted in the psMNIST case. The pictures are for the reader.
    """
    runs = load_runs(experiment)
    if not runs[model]:
        return
    run = runs[model][0]

    images, labels, predictions = classify_test_images(run, experiment)
    names = CIFAR_CLASSES if experiment == "scifar10" else [str(k) for k in range(10)]

    correct = np.flatnonzero(predictions == labels)[:n_show]
    wrong = np.flatnonzero(predictions != labels)[:n_show]

    fig, axes = plt.subplots(2, n_show, figsize=(1.5*n_show, 3.4))
    for row, (indx, title) in enumerate(((correct, "Correct"), (wrong, "Incorrect"))):
        for col in range(n_show):
            ax = axes[row, col]
            if col >= len(indx):
                ax.axis("off")
                continue
            k = indx[col]
            show_image(ax, images[k], experiment)
            ax.set_title(f"{names[labels[k]]} $\\to$ {names[predictions[k]]}", fontsize=8)
        axes[row, 0].set_ylabel(title, fontsize=10)

    plt.tight_layout()
    figpath.mkdir(parents=True, exist_ok=True)
    plt.savefig(figpath / f"{experiment}_examples_{LABELS[model].lower()}.pdf")
    plt.close()


def print_test_results(experiment):
    """Summary table: accuracy over seeds, and time per epoch."""
    runs = load_runs(experiment)
    print(f"\n{experiment}")
    print("model\t params\t seeds\t acc mean\t acc min\t acc max\t s/epoch")
    for model in MODELS:
        if not runs[model]:
            continue
        acc = 100 * np.array([r["results"]["test_at_best_val"] for r in runs[model]])
        epoch_time = np.array([r["results"]["epoch_time"] for r in runs[model]])
        nparams = runs[model][0]["results"]["num_params"]
        print(f"{LABELS[model]}\t {nparams}\t {len(acc)}\t {acc.mean():.2f}\t\t "
              f"{acc.min():.2f}\t\t {acc.max():.2f}\t\t {epoch_time.mean():.1f}")


if __name__ == "__main__":
    for experiment in ("psmnist", "scifar10"):
        plot_accuracy(experiment)
        for model in MODELS:
            plot_example_predictions(experiment, model)
        print_test_results(experiment)
