"""Time inference for the trained REN and R2DN models on every task.

Models are timed as follows: a batch of one is run over HORIZON time steps
and the result divided by HORIZON, giving the cost of a single model call. That
is what the system identification, observer and feedback control models cost in
deployment, since they are evaluated one time step at a time. The image
classification models take a whole image as one call, so their inference time is
the per-call time multiplied by the length of the image sequence.

Explicit model parameters are built once beforehand and excluded from the
timing, as in deployment where the direct parameterization is evaluated at
initialisation rather than on every call.

Code generated by Claude code, checked by Nic Barbara.
"""
import jax
from pathlib import Path

from robustnn import ren
from robustnn import r2dn
from robustnn.timing import time_explicit_forwards

from utils import utils

dirpath = Path(__file__).resolve().parent
jax.config.update("jax_default_matmul_precision", "highest")

HORIZON = 2000
SEQUENCE_LENGTH = {"psmnist": 784, "scifar10": 1024}

TASKS = ["f16", "pde", "youla", "psmnist", "scifar10"]
NETWORKS = ["contracting_ren", "contracting_r2dn"]


def build_model(config, params):
    """Rebuild a trained model. Input and output sizes come from the saved
    parameters, so each task's dimensions do not have to be repeated here."""
    
    p = params["params"]
    nu = p["B2"].shape[1]
    identity_output = "C2" not in p
    ny = config["nx"] if identity_output else p["C2"].shape[0]
    kwargs = {
        "activation": utils.get_activation(config["activation"]),
        "init_method": config["init_method"],
        "do_polar_param": config["polar"],
        "identity_output": identity_output,
    }
    if config["network"] == "contracting_ren":
        return ren.ContractingREN(nu, config["nx"], config["nv"], ny, **kwargs)
    
    return r2dn.ContractingR2DN(
        nu, config["nx"], config["nv"], ny, config["nh"], **kwargs
    )


def time_inference(experiment, network):
    """Mean time for one inference, averaged over every trained model.

    Each model is timed once. The models for a task differ only in their weight
    values, which cannot affect timing, and each measurement already averages
    HORIZON model calls.
    """
    
    files = sorted((dirpath / f"../results/{experiment}").glob(f"*{network}*.pickle"))
    total = 0.0
    for f in files:
        config, params, _ = utils.load_results(f)
        model = build_model(config, params)

        # Dummy inputs: neither model branches on its input, so only shape matters
        key = jax.random.key(0)
        inputs = jax.random.normal(key, (HORIZON, 1, model.input_size))
        states = model.initialize_carry(key, inputs[0].shape)
        explicit = model.direct_to_explicit(params)

        _, eval_time = time_explicit_forwards(
            model, params, explicit, states, inputs, n_repeats=1
        )
        total += eval_time / HORIZON

    return total / len(files) * SEQUENCE_LENGTH.get(experiment, 1)


times = {}
for experiment in TASKS:
    for network in NETWORKS:
        times[(experiment, network)] = time_inference(experiment, network)
        print(f"{experiment:10s} {network:18s} {times[(experiment, network)]:.6g} s",
              flush=True)

print("\nRows for Table~\\ref{tab:timing} (times in the units of your choice):")
for experiment in TASKS:
    a = times[(experiment, "contracting_ren")]
    b = times[(experiment, "contracting_r2dn")]
    print(f"  {experiment:10s} REN {a:.6g} s   R2DN {b:.6g} s   speedup {a/b:.1f}x")
