"""Final experiments: REN vs R2DN on sequential image classification.

Runs the architectures chosen by the Stage 3 tuning sweeps over several random
seeds and saves the results to `results/psmnist/` and `results/scifar10/`.
See `notes/ren_seq_benchmark_log.md` for the sweeps behind each choice.

Usage:
    python train_sequential_imagecfn.py              # both tasks
    python train_sequential_imagecfn.py --task psmnist
    python train_sequential_imagecfn.py --task scifar10

R2DN runs come first and REN runs last, so the cheap results land early. Runs
already on disk are skipped, so this can be stopped and restarted.

Code generated by Claude code, checked by Nic Barbara.
"""
import argparse
import jax
from pathlib import Path

dirpath = Path(__file__).resolve().parent

from utils import utils
from utils import seqcls

jax.config.update("jax_default_matmul_precision", "highest")

SEEDS = range(3)

# Architecture and schedule chosen by the tuning sweeps
CONFIGS = {
    "psmnist": {
        "nx": 96, 
        "nv": 152, 
        "layers": 2,
        "epochs": 150, 
        "lr_cuts": (90, 130),
    },
    "scifar10": {
        "nx": 128, 
        "nv": 78, 
        "layers": 2,
        "epochs": 600, 
        "lr_cuts": (120, 550),
    },
}

# Shared by both tasks
SCHEDULE = {
    "batchsize": 512,
    "lr": 1e-3,
    "activation": "relu",
    "init_method": "long_memory",
    "augment": True,
    "tag": "final",
}

# R2DN first: it is 5-9x faster per epoch, so all the cheap results are in
# before the expensive REN runs start.
NETWORKS = ["contracting_r2dn", "contracting_ren"]


def build_configs(task, seed):
    """REN and R2DN configs for a task, matched on parameter count."""
    arch = CONFIGS[task]
    ren = seqcls.default_config()
    ren.update(SCHEDULE)
    ren.update({
        "experiment": task,
        "network": "contracting_ren",
        "nx": arch["nx"],
        "nv": arch["nv"],
        "epochs": arch["epochs"],
        "lr_cuts": arch["lr_cuts"],
        "seed": seed,
    })
    r2dn = seqcls.matched_r2dn_config(ren, seqcls.TASKS[task], arch["layers"])
    return {"contracting_ren": ren, "contracting_r2dn": r2dn}


def main(tasks):
    for network in NETWORKS:
        for task in tasks:
            for seed in SEEDS:
                config = build_configs(task, seed)[network]
                filepath, fname = utils.generate_fname(config)
                if filepath.exists():
                    print(f"Skipping {fname}, results already exist.")
                    continue
                seqcls.print_summary(config, seqcls.run(config))


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--task", default="all", choices=["all"] + list(CONFIGS))
    args = parser.parse_args()
    main(list(CONFIGS) if args.task == "all" else [args.task])
